services:
  db:
    image: mysql:8.0
    container_name: bt_mysql
    restart: unless-stopped
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: bt_web
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6009:8000"

volumes:
  db_data:
